---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: stub.dev www.stub.dev localhost:31415
    timezone: Europe/London
  vars_files:
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - composer
    - phpcommon
    - app